steps:
  - pwsh: |
      if ($env:Build_Reason -ne 'Schedule')
      {
        Write-Error "Only scheduled runs are allowed in this pipeline!"
      }
      Write-Host "This is a scheduled run!" -ForegroundColor Green
    displayName: 'Allow only scheduled runs'