# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/microsoftgraph/microsoft-graph-docs'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'msgraph-sdk-raptor/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'msgraph-sdk-raptor/CsharpV1Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'