# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'git clone https://github.com/microsoftgraph/microsoft-graph-docs'
  displayName: 'Clone Docs Repo for Snippets'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'msgraph-sdk-raptor/**/*.csproj' # to prevent building docs repo, do not change path to wildcard here
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build all'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/CsharpBetaTests.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Csharp Beta Compilation Tests'