resources:
  repositories:
    - repository: microsoft-graph-docs
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/microsoft-graph-docs
      ref: master
    - repository: apidoctor
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/apidoctor
      ref: master
    - repository: microsoft-graph-explorer-api
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/microsoft-graph-explorer-api
      ref: dev
    - repository: MSGraph-SDK-Code-Generator
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/MSGraph-SDK-Code-Generator
      ref: master
    - repository: msgraph-sdk-dotnet
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/msgraph-sdk-dotnet
      ref: dev
    - repository: msgraph-metadata
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/msgraph-metadata