# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
# Variables that are shared

parameters:
- name: metadataURL
  type: string
  default: 'https://graph.microsoft.com/stagingv1.0/`$metadata'

- name: metadataVersion
  type: string
  default: 'v1.0'

variables:
  buildConfiguration: 'Release'
  typewriterSolution: 'MSGraph-SDK-Code-Generator/**/Typewriter.sln'
  apidoctorSolution: 'apidoctor/**/*.sln'
  snippetLanguages: 'C#' # possible values: 'C#,JavaScript,Objective-C,Java'
  runSettingsFile: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/CSharpArbitraryDllTests/Test.runsettings'
  metadataURL: ${{ parameters.metadataURL }}
  metadataVersion: ${{ parameters.metadataVersion }}