parameters:
  projectFileName: JavaV1Tests
  runName: 'V1 Java Snippet Compilation Tests'
  testType: 'Compilation'
steps:
- template: common-templates/use-dotnet-sdk.yml

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: msgraph-sdk-raptor/**/${{ parameters.projectFileName }}.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Projects'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/${{ parameters.projectFileName }}.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --results-directory $(Agent.TempDirectory) --settings $(Build.SourcesDirectory)/msgraph-sdk-raptor/${{ parameters.projectFileName}}/Test.runsettings'
    publishTestResults: false
  displayName: '${{ parameters.projectFileName }} ${{ parameters.testType }} Tests'
  continueOnError: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    searchFolder: '$(Agent.TempDirectory)'
    testResultsFiles: '**/*.trx'
    testRunTitle: '${{ parameters.runName }}'
  displayName: 'Publish Test Results'