parameters:
  projectFileName: JavaV1Tests
  runName: 'V1 Java Snippet Compilation Tests'
  testType: 'Compilation'
steps:
- template: common-templates/use-dotnet-sdk.yml

- task: NuGetToolInstaller@1
  displayName: 'Install Nuget 5.9.x'
  inputs:
     versionSpec: 5.9.1
     checkLatest: true # Optional

- task: NuGetCommand@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
# Visual Studio build
# Build with MSBuild and set the Visual Studio version property
- task: VSBuild@1
  inputs:
    solution: '**\*.sln' 
    vsVersion: 'latest'
    configuration: $(BuildConfiguration)
    clean: true
    restoreNugetPackages: true
    msbuildArchitecture: x64
    logProjectEvents: true # Optional
    logFileVerbosity: 'normal' # Optional. Options: quiet, minimal, normal, detailed, diagnostic

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg' 
    versionSelector: 'latestStable' 

- task: VSTest@2
  continueOnError: true
  inputs:
    runInParallel: false
    rerunFailedTests: True
    rerunMaxAttempts: 5
    testAssemblyVer2: | # Required when testSelector == TestAssemblies
      **\*CsharpV1ExecutionTests*.dll
      !**\*TestAdapter.dll
      !**\obj\**

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    searchFolder: '$(Agent.TempDirectory)'
    testResultsFiles: '**/*.trx;**/*-TestResults.xml'
    testRunTitle: '${{ parameters.runName }}'
  displayName: 'Publish Test Results'