parameters:
  projectFileName: JavaV1Tests
  runName: 'V1 Java Snippet Compilation Tests'
  testType: 'Compilation'
steps:
- template: common-templates/use-dotnet-sdk.yml

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: msgraph-sdk-raptor/**/${{ parameters.projectFileName }}.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Projects'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg' # Options: nugetOrg, customFeed, netShare
    versionSelector: 'latestStable' # Required when packageFeedSelector == NugetOrg || PackageFeedSelector == CustomFeed# Options: latestPreRelease, latestStable, specificVersion

- task: VSTest@2
  inputs:
     testSelector: 'testAssemblies'
     testAssemblyVer2: |
        **\*CsharpV1ExecutionTests*.dll
        !**\*TestAdapter.dll
        !**\obj\**
     runInParallel: true
     runTestsInIsolation: true
     codeCoverageEnabled: true
     publishRunAttachments: true
     diagnosticsEnabled: true
     rerunFailedThreshold: 50
     rerunType: basedOnTestFailurePercentage
     rerunMaxAttempts: 5
     distributionBatchType: 'basedOnTestCases'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/${{ parameters.projectFileName }}.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --results-directory $(Agent.TempDirectory) --settings $(Build.SourcesDirectory)/msgraph-sdk-raptor/${{ parameters.projectFileName}}/Test.runsettings'
    publishTestResults: false
  displayName: '${{ parameters.projectFileName }} ${{ parameters.testType }} Tests'
  continueOnError: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    searchFolder: '$(Agent.TempDirectory)'
    testResultsFiles: '**/*.trx'
    testRunTitle: '${{ parameters.runName }}'
  displayName: 'Publish Test Results'