parameters:
  projectFileName: JavaV1Tests
  runName: 'V1 Java Snippet Compilation Tests'
  testType: 'Compilation'
steps:
- template: common-templates/use-dotnet-sdk.yml

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: msgraph-sdk-raptor/**/${{ parameters.projectFileName }}.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Projects'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg' # Options: nugetOrg, customFeed, netShare
    versionSelector: 'latestStable' # Required when packageFeedSelector == NugetOrg || PackageFeedSelector == CustomFeed# Options: latestPreRelease, latestStable, specificVersion

- task: VSTest@2
  continueOnError: true
  inputs:
     testSelector: 'testAssemblies'
     testAssemblyVer2: |
        **\*CsharpV1ExecutionTests*.dll
        !**\*TestAdapter.dll
        !**\obj\**
         !**\bin\**\ref\**
     runInParallel: true
     runTestsInIsolation: true
     codeCoverageEnabled: true
     publishRunAttachments: true
     diagnosticsEnabled: true
     rerunFailedThreshold: 30
     collectDumpOn: 'always'
     rerunMaxAttempts: 5
     rerunFailedTests: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: |
        **/TEST-*.xml
        **/*.trx
    mergeTestResults: false # Optional
    failTaskOnFailedTests: false # Optional
    publishRunAttachments: true # Optional
  displayName: "Publish Test Results"