# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
# contains an end to end validation pipeline using C# compilation tests for PROD V1 metadata

trigger: none
pr: none
schedules:
- cron: "0 12 * * *" # everyday at noon
  displayName: 'Daily PROD V1 Validation Pipeline'
  branches:
    include:
    - dev
  always: true

resources:
  repositories:
    - repository: microsoft-graph-docs
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/microsoft-graph-docs
      ref: main
    - repository: apidoctor
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/apidoctor
      ref: master
    - repository: microsoft-graph-devx-api
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/microsoft-graph-devx-api
      ref: dev
    - repository: MSGraph-SDK-Code-Generator
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/MSGraph-SDK-Code-Generator
      ref: main
    - repository: msgraph-sdk-dotnet
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/msgraph-sdk-dotnet
      ref: dev
    - repository: msgraph-metadata
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/msgraph-metadata

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: e2e-templates/variables.yml
    parameters:
      metadataURL: 'https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/v1.0_metadata.xml'
      metadataVersion: 'v1.0'

steps:
  - template: common-templates/allow-only-scheduled-runs.yml
  - template: e2e-templates/steps.yml
