# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
# contains an end to end validation pipeline using C# compilation tests for staging V1 metadata

trigger: none
pr: none
schedules:
- cron: "0 12 * * *" # everyday at noon
  displayName: 'Daily Staging V1 Validation Pipeline'
  branches:
    include:
    - dev
  always: true

extends:
  template: e2e-templates/resources.yml

parameters:
- name: shouldRunKnownFailures
  displayName: 'Should we run known failure tests?'
  type: boolean
  default: true

- name: metadataURL
  displayName: 'URL for metadata for which SDK generation will happen:'
  type: string
  default: 'https://graph.microsoft.com/stagingv1.0/$metadata'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: e2e-templates/variables.yml
    parameters:
      metadataURL: ${{ parameters.metadataURL }}
      metadataVersion: 'v1.0'

steps:
  - template: e2e-templates/steps.yml
    parameters:
      shouldRunKnownFailures: ${{ parameters.shouldRunKnownFailures }}
